//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCBM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCBM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre {0}.
        /// </summary>
        internal static string AboutBox_String1 {
            get {
                return ResourceManager.GetString("AboutBox_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão {0}.
        /// </summary>
        internal static string AboutBox_String2 {
            get {
                return ResourceManager.GetString("AboutBox_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma Atual: .
        /// </summary>
        internal static string AboutCurrentLanguage {
            get {
                return ResourceManager.GetString("AboutCurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradutor: .
        /// </summary>
        internal static string AboutTranslator {
            get {
                return ResourceManager.GetString("AboutTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato: .
        /// </summary>
        internal static string AboutTranslatorContact {
            get {
                return ResourceManager.GetString("AboutTranslatorContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão .
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_file_32 {
            get {
                object obj = ResourceManager.GetObject("add_file_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_folder_32 {
            get {
                object obj = ResourceManager.GetObject("add_folder_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap additional_information_16 {
            get {
                object obj = ResourceManager.GetObject("additional_information_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos os arquivos foram excluídos com sucesso!.
        /// </summary>
        internal static string AllFilesSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("AllFilesSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiiTDB.zip não encontrado, gostaria de baixá-lo agora?.
        /// </summary>
        internal static string AskDownloadWiiTDB {
            get {
                return ResourceManager.GetString("AskDownloadWiiTDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software gerenciador de arquivos ISO e GCM de Nintendo GameCube..
        /// </summary>
        internal static string AssemblyInfo_Description {
            get {
                return ResourceManager.GetString("AssemblyInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATENÇÃO!.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap box_16 {
            get {
                object obj = ResourceManager.GetObject("box_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap box_32 {
            get {
                object obj = ResourceManager.GetObject("box_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap burn_cd_16 {
            get {
                object obj = ResourceManager.GetObject("burn-cd_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap burn_cd_32 {
            get {
                object obj = ResourceManager.GetObject("burn-cd_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel_16 {
            get {
                object obj = ResourceManager.GetObject("cancel-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel_32 {
            get {
                object obj = ResourceManager.GetObject("cancel_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível abrir duas instâncias deste programa!.
        /// </summary>
        internal static string CannotOpenTwoInstances {
            get {
                return ResourceManager.GetString("CannotOpenTwoInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERRO] Não foi possível abrir o arquivo de imagem..
        /// </summary>
        internal static string CantOpenImage {
            get {
                return ResourceManager.GetString("CantOpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, vá em &apos;Opções&apos;-&gt; &apos;Configurações.
        /// </summary>
        internal static string CheckUSBGXFlow_String1 {
            get {
                return ResourceManager.GetString("CheckUSBGXFlow_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depois vá em &apos;Capas&apos; -&gt; &apos;Sincronizar&apos; e marque a opção &apos;Ativar transferência de capas entre dispositivos&apos;..
        /// </summary>
        internal static string CheckUSBGXFlow_String2 {
            get {
                return ResourceManager.GetString("CheckUSBGXFlow_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depois, na mesma aba, vá em &apos;Configuração do carregador USB (Transferir Capas)&apos; e ajuste os diretórios das capas (Disco, 2D, 3D e Completo) do USB Loader GX ou WiiFlow em &apos;Configuração do carregador USB (Transferir Capas)&apos;, apontando para os respectivos diretórios dentro do dispositivo de destino..
        /// </summary>
        internal static string CheckUSBGXFlow_String3 {
            get {
                return ResourceManager.GetString("CheckUSBGXFlow_String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clear_icon {
            get {
                object obj = ResourceManager.GetObject("Clear-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente limpar os dados de registro?.
        /// </summary>
        internal static string ClearLog {
            get {
                return ResourceManager.GetString("ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem dados de registro para limpar!.
        /// </summary>
        internal static string ClearLogNotFound {
            get {
                return ResourceManager.GetString("ClearLogNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [INFO] Não foi possível limpar a pasta temporária!.
        /// </summary>
        internal static string ClearTemp_String1 {
            get {
                return ResourceManager.GetString("ClearTemp_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível limpar a pasta temporária!.
        /// </summary>
        internal static string ClearTemp_String2 {
            get {
                return ResourceManager.GetString("ClearTemp_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap compact_file_16 {
            get {
                object obj = ResourceManager.GetObject("compact_file_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap compact_file_32 {
            get {
                object obj = ResourceManager.GetObject("compact_file_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap conected_16 {
            get {
                object obj = ResourceManager.GetObject("conected_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap config_16 {
            get {
                object obj = ResourceManager.GetObject("config_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap convert_16 {
            get {
                object obj = ResourceManager.GetObject("convert_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap convert_32 {
            get {
                object obj = ResourceManager.GetObject("convert_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Status: Trabalhando....
        /// </summary>
        internal static string ConvertElfDol_String1 {
            get {
                return ResourceManager.GetString("ConvertElfDol_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Status: Não respondendo!.
        /// </summary>
        internal static string ConvertElfDol_String2 {
            get {
                return ResourceManager.GetString("ConvertElfDol_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Status: Completo!.
        /// </summary>
        internal static string ConvertElfDol_String3 {
            get {
                return ResourceManager.GetString("ConvertElfDol_String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Status [ERRO]: Formato de arquivo não reconhecido!.
        /// </summary>
        internal static string ConvertElfDol_String4 {
            get {
                return ResourceManager.GetString("ConvertElfDol_String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferindo arquivo....
        /// </summary>
        internal static string CopyTask_String1 {
            get {
                return ResourceManager.GetString("CopyTask_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalando jogo... .
        /// </summary>
        internal static string CopyTask_String2 {
            get {
                return ResourceManager.GetString("CopyTask_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tranferência finalizada!.
        /// </summary>
        internal static string CopyTask_String3 {
            get {
                return ResourceManager.GetString("CopyTask_String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogo instalado!.
        /// </summary>
        internal static string CopyTask_String4 {
            get {
                return ResourceManager.GetString("CopyTask_String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% Completo!.
        /// </summary>
        internal static string CopyTask_String5 {
            get {
                return ResourceManager.GetString("CopyTask_String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferência finalizada!.
        /// </summary>
        internal static string CopyTask_String6 {
            get {
                return ResourceManager.GetString("CopyTask_String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe pasta GAMES, criar pasta agora?.
        /// </summary>
        internal static string CreateGamesFolder {
            get {
                return ResourceManager.GetString("CreateGamesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este é um dispositivo válido, mas não existe pasta GAMES, criar pasta agora?.
        /// </summary>
        internal static string CreateGamesFolderNow {
            get {
                return ResourceManager.GetString("CreateGamesFolderNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap csv_16 {
            get {
                object obj = ResourceManager.GetObject("csv_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cursor_Select_icon {
            get {
                object obj = ResourceManager.GetObject("Cursor-Select-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_16 {
            get {
                object obj = ResourceManager.GetObject("delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_file_32 {
            get {
                object obj = ResourceManager.GetObject("delete_file_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espaço disponível: .
        /// </summary>
        internal static string DestinyDrive_AvailableSpace {
            get {
                return ResourceManager.GetString("DestinyDrive_AvailableSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espaço total: .
        /// </summary>
        internal static string DestinyDrive_TotalSpace {
            get {
                return ResourceManager.GetString("DestinyDrive_TotalSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Devices_drive_harddisk_usb_icon {
            get {
                object obj = ResourceManager.GetObject("Devices-drive-harddisk-usb-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente excluir o(s) arquivo(s) ? .
        /// </summary>
        internal static string DialogResultDeleteGame_ReallyDeleteFile_String1 {
            get {
                return ResourceManager.GetString("DialogResultDeleteGame_ReallyDeleteFile_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse procedimento é irreversível e não será possivel recuperar o(s) arquivo(s)!.
        /// </summary>
        internal static string DialogResultDeleteGame_ReallyDeleteFile_String2 {
            get {
                return ResourceManager.GetString("DialogResultDeleteGame_ReallyDeleteFile_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disco 1.
        /// </summary>
        internal static string Disc1 {
            get {
                return ResourceManager.GetString("Disc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disco 2.
        /// </summary>
        internal static string Disc2 {
            get {
                return ResourceManager.GetString("Disc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Arquivo.
        /// </summary>
        internal static string DisplayFilesSelected_FileName {
            get {
                return ResourceManager.GetString("DisplayFilesSelected_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho do Arquivo.
        /// </summary>
        internal static string DisplayFilesSelected_FilePath {
            get {
                return ResourceManager.GetString("DisplayFilesSelected_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [INFO] Encontrado(s) .
        /// </summary>
        internal static string DisplayFilesSelected_Found_String1 {
            get {
                return ResourceManager.GetString("DisplayFilesSelected_Found_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  arquivo(s) com extensão ..
        /// </summary>
        internal static string DisplayFilesSelected_Found_String2 {
            get {
                return ResourceManager.GetString("DisplayFilesSelected_Found_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontrado(s) .
        /// </summary>
        internal static string DisplayFilesSelected_Found_String3 {
            get {
                return ResourceManager.GetString("DisplayFilesSelected_Found_String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho.
        /// </summary>
        internal static string DisplayFilesSelected_Size {
            get {
                return ResourceManager.GetString("DisplayFilesSelected_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dolphin_emulator_16 {
            get {
                object obj = ResourceManager.GetObject("dolphin_emulator_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulador não encontrado!.
        /// </summary>
        internal static string DolphinEmulator_Not_Found_String_1 {
            get {
                return ResourceManager.GetString("DolphinEmulator_Not_Found_String_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, configure o camihno até o executável do emulador Dolphin (dolphin.exe)..
        /// </summary>
        internal static string DolphinEmulator_Not_Found_String_2 {
            get {
                return ResourceManager.GetString("DolphinEmulator_Not_Found_String_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap donate {
            get {
                object obj = ResourceManager.GetObject("donate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [INFO] Baixando capas (3D)... .
        /// </summary>
        internal static string Download3DCover {
            get {
                return ResourceManager.GetString("Download3DCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [ERRO] Falha ao efetuar download da capa (3D)!.
        /// </summary>
        internal static string Download3DCoverError {
            get {
                return ResourceManager.GetString("Download3DCoverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [INFO] Baixando capas (Disco)... .
        /// </summary>
        internal static string DownloadDiscCover {
            get {
                return ResourceManager.GetString("DownloadDiscCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [ERRO] Falha ao efetuar download da capa (Disco)!.
        /// </summary>
        internal static string DownloadDiscCoverError {
            get {
                return ResourceManager.GetString("DownloadDiscCoverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Baixando WiiTDB.zip ... .
        /// </summary>
        internal static string DownloadingWiiTDB_String1 {
            get {
                return ResourceManager.GetString("DownloadingWiiTDB_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Extraindo WiiTDB.xml ....
        /// </summary>
        internal static string DownloadingWiiTDB_String2 {
            get {
                return ResourceManager.GetString("DownloadingWiiTDB_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Processo concluído!.
        /// </summary>
        internal static string DownloadingWiiTDB_String3 {
            get {
                return ResourceManager.GetString("DownloadingWiiTDB_String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lista de jogos está vazia!.
        /// </summary>
        internal static string EmptyGamesList {
            get {
                return ResourceManager.GetString("EmptyGamesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eraser_16 {
            get {
                object obj = ResourceManager.GetObject("eraser_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eraser_32 {
            get {
                object obj = ResourceManager.GetObject("eraser_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [ERRO] .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRB_Adults_Only_18_ {
            get {
                object obj = ResourceManager.GetObject("ESRB_Adults_Only_18_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRB_Adults_Only_18__grayscale {
            get {
                object obj = ResourceManager.GetObject("ESRB_Adults_Only_18+_grayscale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRB_Early_Childhood {
            get {
                object obj = ResourceManager.GetObject("ESRB_Early_Childhood", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRB_Early_Childhood_grayscale {
            get {
                object obj = ResourceManager.GetObject("ESRB_Early_Childhood_grayscale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRB_Everyone {
            get {
                object obj = ResourceManager.GetObject("ESRB_Everyone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRB_Everyone_10_ {
            get {
                object obj = ResourceManager.GetObject("ESRB_Everyone_10_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRB_Everyone_10__grayscale {
            get {
                object obj = ResourceManager.GetObject("ESRB_Everyone_10+_grayscale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRB_Everyone_grayscale {
            get {
                object obj = ResourceManager.GetObject("ESRB_Everyone_grayscale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRB_Mature_17_ {
            get {
                object obj = ResourceManager.GetObject("ESRB_Mature_17_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRB_Mature_17__grayscale {
            get {
                object obj = ResourceManager.GetObject("ESRB_Mature_17+_grayscale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRB_RP {
            get {
                object obj = ResourceManager.GetObject("ESRB_RP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRB_RP_grayscale {
            get {
                object obj = ResourceManager.GetObject("ESRB_RP_grayscale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRB_Teen {
            get {
                object obj = ResourceManager.GetObject("ESRB_Teen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRB_Teen_grayscale {
            get {
                object obj = ResourceManager.GetObject("ESRB_Teen_grayscale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERRO] Não foi possível localizar o arquivo especificado em {0}. Por favor, selecione {1}. Ou clique em cancelar para pular o arquivo atual e tentar continuar..
        /// </summary>
        internal static string ExceptionHelperFileNotFound {
            get {
                return ResourceManager.GetString("ExceptionHelperFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERRO] Não foi possível localizar o arquivo para o disco secundário. Por favor, localize a pasta &apos;{1} [{2}2]&apos; contendo &apos;game.iso&apos;..
        /// </summary>
        internal static string ExceptionHelperFileNotFoundDisc2Scrub {
            get {
                return ResourceManager.GetString("ExceptionHelperFileNotFoundDisc2Scrub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye_16 {
            get {
                object obj = ResourceManager.GetObject("eye_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap facebook_16 {
            get {
                object obj = ResourceManager.GetObject("facebook_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivos (Destino) - Unidade (.
        /// </summary>
        internal static string FilesDestinationUnit {
            get {
                return ResourceManager.GetString("FilesDestinationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lista da Base de Dados está vazia!.
        /// </summary>
        internal static string FilterDatabase_String1 {
            get {
                return ResourceManager.GetString("FilterDatabase_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se o arquivo &apos;wiitdb.xml&apos; estiver instalado corretamente, faça os ajustes necessários nas configurações do programa..
        /// </summary>
        internal static string FilterDatabase_String2 {
            get {
                return ResourceManager.GetString("FilterDatabase_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SUCESSO] Transferência de {0} jogos concluída..
        /// </summary>
        internal static string FinishedInstalling {
            get {
                return ResourceManager.GetString("FinishedInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap format_dvd_32 {
            get {
                object obj = ResourceManager.GetObject("format_dvd_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [INFO] Arquivo(s) ISO/GCM encontrado(s): .
        /// </summary>
        internal static string FoundIsoGcmFiles {
            get {
                return ResourceManager.GetString("FoundIsoGcmFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programa sendo executado em segundo plano!.
        /// </summary>
        internal static string frmMain_Resize_Program {
            get {
                return ResourceManager.GetString("frmMain_Resize_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de jogos exportada para CSV!.
        /// </summary>
        internal static string GameListExportedCSV {
            get {
                return ResourceManager.GetString("GameListExportedCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de jogos exportada para TXT!.
        /// </summary>
        internal static string GameListExportedTXT {
            get {
                return ResourceManager.GetString("GameListExportedTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GameTDB_400 {
            get {
                object obj = ResourceManager.GetObject("GameTDB-400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gbatemp_16 {
            get {
                object obj = ResourceManager.GetObject("gbatemp_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gcbm {
            get {
                object obj = ResourceManager.GetObject("gcbm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese [Brazil].
        /// </summary>
        internal static string GCBM_Language {
            get {
                return ResourceManager.GetString("GCBM_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gcbm_logo {
            get {
                object obj = ResourceManager.GetObject("gcbm_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gcbm_splash_screen {
            get {
                object obj = ResourceManager.GetObject("gcbm_splash_screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laete Meireles.
        /// </summary>
        internal static string GCBM_TranslatedBy {
            get {
                return ResourceManager.GetString("GCBM_TranslatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to laetemn@hotmail.com.
        /// </summary>
        internal static string GCBM_TranslatorContact {
            get {
                return ResourceManager.GetString("GCBM_TranslatorContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo.
        /// </summary>
        internal static string GetAllDrives_Inactive {
            get {
                return ResourceManager.GetString("GetAllDrives_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap github_16 {
            get {
                object obj = ResourceManager.GetObject("github_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap globe_earth_color_64 {
            get {
                object obj = ResourceManager.GetObject("globe-earth-color_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap globe_earth_grayscale_64 {
            get {
                object obj = ResourceManager.GetObject("globe-earth-grayscale_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hash_16 {
            get {
                object obj = ResourceManager.GetObject("hash_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [INFO] Os hashes não são os mesmos!.
        /// </summary>
        internal static string HashesAreNotSame {
            get {
                return ResourceManager.GetString("HashesAreNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap html_16 {
            get {
                object obj = ResourceManager.GetObject("html_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_not_found_1 {
            get {
                object obj = ResourceManager.GetObject("image_not_found_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_not_found_2 {
            get {
                object obj = ResourceManager.GetObject("image_not_found_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [INFO] .
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info_16 {
            get {
                object obj = ResourceManager.GetObject("info_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap information_16 {
            get {
                object obj = ResourceManager.GetObject("information_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap install_16 {
            get {
                object obj = ResourceManager.GetObject("install_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap install_software_32 {
            get {
                object obj = ResourceManager.GetObject("install_software_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Completo!.
        /// </summary>
        internal static string InstallGameScrub_Complete {
            get {
                return ResourceManager.GetString("InstallGameScrub_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esfoliação finalizada....
        /// </summary>
        internal static string InstallGameScrub_DoneScrubbing {
            get {
                return ResourceManager.GetString("InstallGameScrub_DoneScrubbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogo instalado com sucesso!.
        /// </summary>
        internal static string InstallGameScrub_GameInstalled {
            get {
                return ResourceManager.GetString("InstallGameScrub_GameInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Scrubbing... .
        /// </summary>
        internal static string InstallGameScrub_Scrubbing {
            get {
                return ResourceManager.GetString("InstallGameScrub_Scrubbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movendo o disco 2....
        /// </summary>
        internal static string InstallGameScrub_TransferDisc2 {
            get {
                return ResourceManager.GetString("InstallGameScrub_TransferDisc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferindo....
        /// </summary>
        internal static string InstallGameScrub_Transferring {
            get {
                return ResourceManager.GetString("InstallGameScrub_Transferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disco 2 transferido com sucesso!.
        /// </summary>
        internal static string InstallGameScrub_TrasnferredDisc2 {
            get {
                return ResourceManager.GetString("InstallGameScrub_TrasnferredDisc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Não respondendo!.
        /// </summary>
        internal static string InstallGameScrub_Unresponsive {
            get {
                return ResourceManager.GetString("InstallGameScrub_Unresponsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este não é um dispositivo válido!.
        /// </summary>
        internal static string InvalidDrive_String1 {
            get {
                return ResourceManager.GetString("InvalidDrive_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sistema de arquivos detectado é: .
        /// </summary>
        internal static string InvalidDrive_String2 {
            get {
                return ResourceManager.GetString("InvalidDrive_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O app Nintendont suporta somente os sistemas de arquivos FAT32 e exFAT..
        /// </summary>
        internal static string InvalidDrive_String3 {
            get {
                return ResourceManager.GetString("InvalidDrive_String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É altamente recomendado utilizar o sistema de arquivos FAT32 com 32K clusters para garantir o máximo de compatibilidade com jogos de GameCube, Wii, ROM&apos;s, apps, emuladores e tudo mais!.
        /// </summary>
        internal static string InvalidDrive_String4 {
            get {
                return ResourceManager.GetString("InvalidDrive_String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entretanto, você pode utilizar dispositivos .
        /// </summary>
        internal static string InvalidDrive_String5 {
            get {
                return ResourceManager.GetString("InvalidDrive_String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  como armazenamento de BACKUP para arquivos ISO/GCM..
        /// </summary>
        internal static string InvalidDrive_String6 {
            get {
                return ResourceManager.GetString("InvalidDrive_String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O .
        /// </summary>
        internal static string ListHash_String1 {
            get {
                return ResourceManager.GetString("ListHash_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hash do arquivo: .
        /// </summary>
        internal static string ListHash_String2 {
            get {
                return ResourceManager.GetString("ListHash_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvedor.
        /// </summary>
        internal static string LoadDatabase_Developer {
            get {
                return ResourceManager.GetString("LoadDatabase_Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string LoadDatabase_Editor {
            get {
                return ResourceManager.GetString("LoadDatabase_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título do Jogo.
        /// </summary>
        internal static string LoadDatabase_GameTitle {
            get {
                return ResourceManager.GetString("LoadDatabase_GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID (Código do Jogo).
        /// </summary>
        internal static string LoadDatabase_IDGameCode {
            get {
                return ResourceManager.GetString("LoadDatabase_IDGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Região.
        /// </summary>
        internal static string LoadDatabase_Region {
            get {
                return ResourceManager.GetString("LoadDatabase_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string LoadDatabase_Type {
            get {
                return ResourceManager.GetString("LoadDatabase_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disco primário: (disc1).
        /// </summary>
        internal static string LoadISOInfo_String1 {
            get {
                return ResourceManager.GetString("LoadISOInfo_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disco secundário: (disc2).
        /// </summary>
        internal static string LoadISOInfo_String2 {
            get {
                return ResourceManager.GetString("LoadISOInfo_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap log_64 {
            get {
                object obj = ResourceManager.GetObject("log_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap manager_apps_16 {
            get {
                object obj = ResourceManager.GetObject("manager_apps_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap manager_apps_32 {
            get {
                object obj = ResourceManager.GetObject("manager_apps_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRO.
        /// </summary>
        internal static string MetaXml_String_ERRO {
            get {
                return ResourceManager.GetString("MetaXml_String_ERRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo &apos;meta.xml&apos; inválido ou danificado!.
        /// </summary>
        internal static string MetaXml_String1 {
            get {
                return ResourceManager.GetString("MetaXml_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados gravados com sucesso!.
        /// </summary>
        internal static string MetaXml_String2 {
            get {
                return ResourceManager.GetString("MetaXml_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Misc_Download_Database_icon {
            get {
                object obj = ResourceManager.GetObject("Misc-Download-Database-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexão com a internet desativada!.
        /// </summary>
        internal static string NetworkCheck_NetStatus_Offline {
            get {
                return ResourceManager.GetString("NetworkCheck_NetStatus_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexão com a internet estabelecida!.
        /// </summary>
        internal static string NetworkCheck_NetStatus_Online {
            get {
                return ResourceManager.GetString("NetworkCheck_NetStatus_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma conexão com a internet encontrada!.
        /// </summary>
        internal static string NoInternetConnectionFound_String1 {
            get {
                return ResourceManager.GetString("NoInternetConnectionFound_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique se a conexão está ativada nas configurações do programa..
        /// </summary>
        internal static string NoInternetConnectionFound_String2 {
            get {
                return ResourceManager.GetString("NoInternetConnectionFound_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap not_conected_16 {
            get {
                object obj = ResourceManager.GetObject("not_conected_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVISO.
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [ERRO] Não é um arquivo de Nintendo GameCube..
        /// </summary>
        internal static string NotNintendoGameCubeFile {
            get {
                return ResourceManager.GetString("NotNintendoGameCubeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open_folder_16 {
            get {
                object obj = ResourceManager.GetObject("open_folder_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open_folder_32 {
            get {
                object obj = ResourceManager.GetObject("open_folder_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open_folder_64 {
            get {
                object obj = ResourceManager.GetObject("open_folder_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja substituir o arquivo WiiTDB.xml atual? Deseja substituir o WiiTDB atual..
        /// </summary>
        internal static string OverwriteWiiTDBBody {
            get {
                return ResourceManager.GetString("OverwriteWiiTDBBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Substituir WiiTDB.xml?&quot;.
        /// </summary>
        internal static string OverwriteWiiTDBCaption {
            get {
                return ResourceManager.GetString("OverwriteWiiTDBCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plugin_16 {
            get {
                object obj = ResourceManager.GetObject("plugin_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plugin_32 {
            get {
                object obj = ResourceManager.GetObject("plugin_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza de que deseja excluir o plugin?.
        /// </summary>
        internal static string PluginDisplay_String1 {
            get {
                return ResourceManager.GetString("PluginDisplay_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desinstalar.
        /// </summary>
        internal static string PluginDisplay_String2 {
            get {
                return ResourceManager.GetString("PluginDisplay_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo &apos;wiitdb.xml&apos; não foi encontrado!.
        /// </summary>
        internal static string ProcessTaskDelay_String1 {
            get {
                return ResourceManager.GetString("ProcessTaskDelay_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, faça o download do arquivo!.
        /// </summary>
        internal static string ProcessTaskDelay_String2 {
            get {
                return ResourceManager.GetString("ProcessTaskDelay_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algumas funções que dependem desse arquivo não irão funcionar até seja efetuado o download do arquivo!.
        /// </summary>
        internal static string ProcessTaskDelay_String3 {
            get {
                return ResourceManager.GetString("ProcessTaskDelay_String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para efetuar o download do arquivo (requer conexão com a internet), vá até a aba &apos;Base de Dados&apos;, depois em &apos;Ferramentas&apos; -&gt; &apos;Atualização do GameTDB&apos;..
        /// </summary>
        internal static string ProcessTaskDelay_String4 {
            get {
                return ResourceManager.GetString("ProcessTaskDelay_String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A imagem é muito pequena!.
        /// </summary>
        internal static string ReadImage_String1 {
            get {
                return ResourceManager.GetString("ReadImage_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Várias imagens FST?\r\nPor favor, envie-me informações sobre esta imagem..
        /// </summary>
        internal static string ReadImage_String2 {
            get {
                return ResourceManager.GetString("ReadImage_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo &apos;{0}&apos; não encontrado!.
        /// </summary>
        internal static string ReadImage_String3 {
            get {
                return ResourceManager.GetString("ReadImage_String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRO!.
        /// </summary>
        internal static string ReadImage_String4 {
            get {
                return ResourceManager.GetString("ReadImage_String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É recomendável excluir ou mover o arquivo para outro local..
        /// </summary>
        internal static string RecommendedDeleteOrMoveFile {
            get {
                return ResourceManager.GetString("RecommendedDeleteOrMoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum dado disponível para ser exportado!.
        /// </summary>
        internal static string RecordExportedFailed {
            get {
                return ResourceManager.GetString("RecordExportedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro exportado com sucesso!.
        /// </summary>
        internal static string RecordExportedSuccessfully {
            get {
                return ResourceManager.GetString("RecordExportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh_16 {
            get {
                object obj = ResourceManager.GetObject("Refresh_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_32 {
            get {
                object obj = ResourceManager.GetObject("refresh_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Versão da Aplicação: .
        /// </summary>
        internal static string RegisterHeaderLog_ApplicationVersion {
            get {
                return ResourceManager.GetString("RegisterHeaderLog_ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  CLR Versão: .
        /// </summary>
        internal static string RegisterHeaderLog_CLRVersion {
            get {
                return ResourceManager.GetString("RegisterHeaderLog_CLRVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [INFO] Diretório atual do programa: .
        /// </summary>
        internal static string RegisterHeaderLog_CurrentProgramDirectory {
            get {
                return ResourceManager.GetString("RegisterHeaderLog_CurrentProgramDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  gcbm.log é criado..
        /// </summary>
        internal static string RegisterHeaderLog_GcbmLogCreated {
            get {
                return ResourceManager.GetString("RegisterHeaderLog_GcbmLogCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Unidades Lógicas: .
        /// </summary>
        internal static string RegisterHeaderLog_LogicalUnits {
            get {
                return ResourceManager.GetString("RegisterHeaderLog_LogicalUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  OS Versão: .
        /// </summary>
        internal static string RegisterHeaderLog_OSVersion {
            get {
                return ResourceManager.GetString("RegisterHeaderLog_OSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nome do Programa: .
        /// </summary>
        internal static string RegisterHeaderLog_ProgramName {
            get {
                return ResourceManager.GetString("RegisterHeaderLog_ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Conjunto de Trabalho: .
        /// </summary>
        internal static string RegisterHeaderLog_WorkingSet {
            get {
                return ResourceManager.GetString("RegisterHeaderLog_WorkingSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Remove {
            get {
                object obj = ResourceManager.GetObject("Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rename_16 {
            get {
                object obj = ResourceManager.GetObject("rename_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rename_folder_16 {
            get {
                object obj = ResourceManager.GetObject("rename_folder_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [INFO] O diretório temporário padrão foi criado....
        /// </summary>
        internal static string RequiredDirectories_String1 {
            get {
                return ResourceManager.GetString("RequiredDirectories_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [INFO] O diretório temporário padrão já existe... ignorando criação!.
        /// </summary>
        internal static string RequiredDirectories_String2 {
            get {
                return ResourceManager.GetString("RequiredDirectories_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [INFO] Utilizando diretório temporário personalizado!.
        /// </summary>
        internal static string RequiredDirectories_String3 {
            get {
                return ResourceManager.GetString("RequiredDirectories_String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [INFO] Os diretórios de capas foram criados....
        /// </summary>
        internal static string RequiredDirectories_String4 {
            get {
                return ResourceManager.GetString("RequiredDirectories_String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [INFO] Os diretórios de capas já existem... ignorando criação!.
        /// </summary>
        internal static string RequiredDirectories_String5 {
            get {
                return ResourceManager.GetString("RequiredDirectories_String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_32 {
            get {
                object obj = ResourceManager.GetObject("save_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_16 {
            get {
                object obj = ResourceManager.GetObject("search_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search256 {
            get {
                object obj = ResourceManager.GetObject("Search256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search32 {
            get {
                object obj = ResourceManager.GetObject("Search32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma pasta contendo arquivos ISO/GCM:.
        /// </summary>
        internal static string SelectFolderContainingIsoGcmFiles {
            get {
                return ResourceManager.GetString("SelectFolderContainingIsoGcmFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecione um jogo da lista!.
        /// </summary>
        internal static string SelectGameFromList {
            get {
                return ResourceManager.GetString("SelectGameFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecione uma unidade de destino!.
        /// </summary>
        internal static string SelectTargetDrive {
            get {
                return ResourceManager.GetString("SelectTargetDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O servidor informou: Capa 3D não encontrada!.
        /// </summary>
        internal static string ServerReported3DCoverNotFound {
            get {
                return ResourceManager.GetString("ServerReported3DCoverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O servidor informou: Capa Disco não encontrada!.
        /// </summary>
        internal static string ServerReportedDiscCoverNotFound {
            get {
                return ResourceManager.GetString("ServerReportedDiscCoverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O servidor informou: Uma das capas (ou ambas) não foi localizada!.
        /// </summary>
        internal static string ServerReportedOneCoverOrBothNotFound {
            get {
                return ResourceManager.GetString("ServerReportedOneCoverOrBothNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurando diretórios necessários....
        /// </summary>
        internal static string SplashDirectories {
            get {
                return ResourceManager.GetString("SplashDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizado..
        /// </summary>
        internal static string SplashFinished {
            get {
                return ResourceManager.GetString("SplashFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminando....
        /// </summary>
        internal static string SplashFinishing {
            get {
                return ResourceManager.GetString("SplashFinishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade encontrada:.
        /// </summary>
        internal static string SplashFoundDrive {
            get {
                return ResourceManager.GetString("SplashFoundDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificando conexão com a internet....
        /// </summary>
        internal static string SplashNetworkCheck {
            get {
                return ResourceManager.GetString("SplashNetworkCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preenchendo a lista de unidades....
        /// </summary>
        internal static string SplashPopulatingDrives {
            get {
                return ResourceManager.GetString("SplashPopulatingDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SplashSettingUp {
            get {
                return ResourceManager.GetString("SplashSettingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SplashWiiTDB {
            get {
                return ResourceManager.GetString("SplashWiiTDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sync_16 {
            get {
                object obj = ResourceManager.GetObject("sync_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transfer_0002 {
            get {
                object obj = ResourceManager.GetObject("transfer_0002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap txt_16 {
            get {
                object obj = ResourceManager.GetObject("txt_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível gravar os dados no disco!.
        /// </summary>
        internal static string UnableWriteDataDisk {
            get {
                return ResourceManager.GetString("UnableWriteDataDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Região desconhecida!.
        /// </summary>
        internal static string UnknownRegion {
            get {
                return ResourceManager.GetString("UnknownRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update_16 {
            get {
                object obj = ResourceManager.GetObject("update_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update_64 {
            get {
                object obj = ResourceManager.GetObject("update_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Utilities_icon {
            get {
                object obj = ResourceManager.GetObject("Utilities-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap website {
            get {
                object obj = ResourceManager.GetObject("website", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap website_grayscale {
            get {
                object obj = ResourceManager.GetObject("website_grayscale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xml_16 {
            get {
                object obj = ResourceManager.GetObject("xml_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xml_32 {
            get {
                object obj = ResourceManager.GetObject("xml_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
