namespace GCBM.tools.Interop;

public enum IMAPI_MEDIA_WRITE_PROTECT_STATE
{
    IMAPI_WRITEPROTECTED_UNTIL_POWERDOWN = 1,
    IMAPI_WRITEPROTECTED_BY_CARTRIDGE = 2,
    IMAPI_WRITEPROTECTED_BY_MEDIA_SPECIFIC_REASON = 4,
    IMAPI_WRITEPROTECTED_BY_SOFTWARE_WRITE_PROTECT = 8,
    IMAPI_WRITEPROTECTED_BY_DISC_CONTROL_BLOCK = 0x10,
    IMAPI_WRITEPROTECTED_READ_ONLY_MEDIA = 0x4000
}